### ISSUE TITLE
Process for proposing updates

### ISSUE THREAD

**Issue by AndyClifton** [wind-energy/taxonomies-and-vocabularies#1]
@niva83 - love the idea! But what if we want to propose new branches or leaves? Should we just do a pull request?

**Comment by AndyClifton** [comment]
For example, I would like to further subdivide the "Forests" in the external conditions depending on whether or not they lose their leaves, and also by the density of the foliage. There´s lots of examples on the [wikipedia page about Forests](https://en.wikipedia.org/wiki/Forest#Types). What's the best way to proceed?

**Comment by AndyClifton** [comment]
And could you add a few labels to the Github, e.g. "new branch", "change definition", "remove branch"?

**Comment by niva83** [comment]
Hi Andy,

Good points! Probably the best is to do pull request. 
I will add you a collaborator.

**Comment by AndyClifton** [comment]
@niva83: I'd like to see this captured in the readme. Could you add text about this there?

**Comment by niva83** [comment]
@AndyClifton yes sir! The Readme has been updated.

**Comment by niva83** [comment]
> For example, I would like to further subdivide the "Forests" in the external conditions depending on whether or not they lose their leaves, and also by the density of the foliage. There´s lots of examples on the [wikipedia page about Forests](https://en.wikipedia.org/wiki/Forest#Types). What's the best way to proceed?

The taxonomy of external conditions should not have depth more than 4 , thus if you could come up with something that will not add more than 2 depth in the existing taxonomy.
